markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/css/custom.css

site_name: "EKS Checklist"
docs_dir: docs
theme:
  name: "material"
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant  # 추가
    - navigation.tracking  # 추가
    - navigation.indexes  # 추가 - 섹션 인덱스 페이지 사용

nav:
    - Home : 
      - index.md
      - How it works : home/howitworks.md
    - Runbook:
      - General:
        - GEN-001 코드형 인프라 : runbook/general/GEN-001.md
        - GEN-002 GitOps 적용 : runbook/general/GEN-002.md
        - GEN-003 컨테이너 이미지 태그에 latest 미사용 : runbook/general/GEN-003.md
      - Security:
        - SEC-001 EKS 클러스터 API 엔드포인트 접근 제어 : runbook/security/SEC-001.md
        - SEC-002 클러스터 접근 제어(Access entries, aws-auth 컨피그맵) : runbook/security/SEC-002.md
        - SEC-003 IRSA 또는 EKS Pod Identity 기반 권한 부여 : runbook/security/SEC-003.md
        - SEC-004 데이터 플레인 노드에 필수로 필요한 IAM 권한만 부여: runbook/security/SEC-004.md
        - SEC-005 루트 유저가 아닌 유저로 컨테이너 실행: runbook/security/SEC-005.md
        - SEC-006 멀티 태넌시 적용 유무 : runbook/security/SEC-006.md
        - SEC-007 Audit 로그 활성화 : runbook/security/SEC-007.md
        - SEC-008 비정상 접근에 대한 알림 설정 : runbook/security/SEC-008.md
        - SEC-009 Pod-to-Pod 접근 제어 : runbook/security/SEC-009.md
        - SEC-010 PV 암호화 : runbook/security/SEC-010.md
        - SEC-011 Secret 객체 암호화 : runbook/security/SEC-011.md
        - SEC-012 데이터 플레인 사설망 : runbook/security/SEC-012.md
        - SEC-013 컨테이너 이미지 정적 분석 : runbook/security/SEC-013.md
        - SEC-014 읽기 전용 파일시스템 사용 : runbook/security/SEC-014.md
      - Scalability:
        - SCL-001 Karpenter 사용 : runbook/scalability/SCL-001.md
        - SCL-002 Karpenter 전용 노드 그룹 혹은 Fargate 사용 : runbook/scalability/SCL-002.md
        - SCL-003 Spot 노드 사용시 Spot 중지 핸들러 적용 : runbook/scalability/SCL-003.md
        - SCL-004 중요 Pod에 노드 삭제 방지용 Label 부여 : runbook/scalability/SCL-004.md
        - SCL-005 Application에 Graceful shutdown 적용 : runbook/scalability/SCL-005.md
        - SCL-006 노드 확장/축소 정책 적용 : runbook/scalability/SCL-006.md
        - SCL-007 다양한 인스턴스 타입 사용 : runbook/scalability/SCL-007.md
      - Reliability:
        - REL-001 싱글톤 Pod 미사용 : runbook/reliability/REL-001.md
        - REL-002 2개 이상의 Pod 복제본 사용 : runbook/reliability/REL-002.md
        - REL-003 동일한 역할을 하는 Pod를 다수의 노드에 분산 배포 : runbook/reliability/REL-003.md
        - REL-004 HPA 적용 : runbook/reliability/REL-004.md
        - REL-005 Probe(Startup, Readiness, Liveness) 적용 : runbook/reliability/REL-005.md
        - REL-006 중요 워크로드에 대한 PDB(Pod Distruption Budget) 적용 : runbook/reliability/REL-006.md
        - REL-007 애플리케이션에 적절한 CPU/RAM 할당 : runbook/reliability/REL-007.md
        - REL-008 애플리케이션 중요도에 따른 QoS 적용 : runbook/reliability/REL-008.md
        - REL-009 인프라 및 애플리케이션 모니터링 스택 적용 : runbook/reliability/REL-009.md
        - REL-010 반영구 저장소에 애플리케이션 로그 저장 : runbook/reliability/REL-010.md
        - REL-011 오토스케일링 그룹 기반 관리형 노드 그룹 생성 : runbook/reliability/REL-011.md
        - REL-012 Cluster Autoscaler 적용 : runbook/reliability/REL-012.md
        - REL-013 Karpenter 기반 노드 생성 : runbook/reliability/REL-013.md
        - REL-014 다수의 가용 영역에 데이터 플레인 노드 배포 : runbook/reliability/REL-014.md
        - REL-015 PV 사용시 volume affinity 위반 사항 체크 : runbook/reliability/REL-015.md
        - REL-016 CoreDNS에 HPA 적용 : runbook/reliability/REL-016.md
        - REL-017 DNS 캐시 적용 : runbook/reliability/REL-017.md
        - REL-018 Karpenter 사용시 DaemonSet에 Priority Class 부여 : runbook/reliability/REL-018.md
      - Network:
        - NET-001 VPC 서브넷에 충분한 IP 대역대 확보: runbook/network/NET-001.md
        - NET-002 Pod에 부여할 IP 부족시 알림 설정: runbook/network/NET-002.md
        - NET-003 VPC CNI의 Prefix 모드 사용: runbook/network/NET-003.md
        - NET-004 사용 사례에 맞는 로드밸런서 사용(ALB or NLB): runbook/network/NET-004.md
        - NET-005 AWS Load Balancer Controller 사용: runbook/network/NET-005.md
        - NET-006 ALB/NLB의 대상으로 Pod의 IP 사용: runbook/network/NET-006.md
        - NET-007 Pod Readiness Gate 적용: runbook/network/NET-007.md
        - NET-008 kube-proxy에 IPVS 모드 적용: runbook/network/NET-008.md
        - NET-009 Endpoint 대신 EndpointSlices 사용: runbook/network/NET-009.md
      - Cost:
        - COST-001 kubecost 설치 : runbook/cost/COST-001.md